GlobalPlanner:
  allow_unknown: true
  default_tolerance: 0.1
  visualize_potential: true
  use_dijkstra: false 
  use_quadratic: true
  use_grid_path: true
  old_navfn_behavior: false
 
  lethal_cost: 253
  neutral_cost:  40 #40
  cost_factor: 50 #0.15
  publish_potential: true
  orientation_mode: 0
  orientation_window_size: 1
  
  max_vel_x: 0.55  #maximum velocity oflinear
  min_vel_x: 0.1  #minimum velocity of linear 

