local_costmap:
  global_frame: odom #里程計座標系
  robot_base_frame: base_link #機器人座標系

  update_frequency: 10.0 #代價地圖更新频率 建議設高
  publish_frequency: 10.0 #代價地圖的發布頻率
  transform_tolerance: 0.5 #等待座標轉換發布信息的超時時間
  inflationn_radius: 0.8  #膨脹半徑
  cost_scaling_factor: 3.0

  static_map: false  #不需要靜態地圖，可以提升導航效果
  rolling_window: true #是否使用动态窗口，默认为false，在静态的全局地图中，地图不会变化
  width: 3 # 局部地图宽度 单位是 m
  height: 3 # 局部地图高度 单位是 m
  resolution: 0.05 # 局部地图分辨率 单位是 m，一般与静态地图分辨率保持一致

